name: Vibrant Wellness
favicon: null
layout_spectrum: 0.6064400761388242
typography_spectrum: 0.5723380576819181
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f5cd'
    - '#0f1a2e'
    - '#99a380'
    - '#9c3a37'
    - '#e8d094'
  brandStrength: 0.2941482556052506
  lightness: 0.046982645988464355
  saturation: 0.580671866890043
  rhythmicContrast: 0.3759782414417714
purpose: []
